# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "Jinqu-graden"

# ç½‘é¡µçš„æ ‡é¢˜
title: "é‡‘æ›²çš„å¤ªç©ºèˆ±"
# ç½‘ç«™çš„ä¸»æ ‡é¢˜
name: "Hiï¼Œè¿™é‡Œæ˜¯é‡‘æ›²"
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "æ¬¢è¿æ¥åˆ°æˆ‘çš„å°å°å¤ªç©ºèˆ±ğŸ’¨"

# åˆ†é¡µé…ç½®
# æ¯é¡µæ–‡ç« æ•°é‡
paginate: 9

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
permalink: /:title/
paginate_path: /page:num/
plugins:
  - jekyll-paginate

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
lazyimages: "disabled"
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
